using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using Kotlet.TestData;
using Xunit;

namespace Kotlet.Api.IntegrationTests.Persistence;

/// <summary>
/// Guards the shared fixture. It is generated by running the real seeder against the real
/// schema, so a model change that the seeder has not caught up with fails here — loudly and in
/// one place — instead of surfacing as a confusing failure in the benchmark or the browser tests.
/// </summary>
public sealed class SharedTestDataTests(SeededWebApplicationFactory factory)
    : IClassFixture<SeededWebApplicationFactory>
{
    [Fact]
    public async Task SeededAccount_CanSignInAndSeeItsHousehold()
    {
        var client = factory.CreateClient();

        var login = await client.PostAsJsonAsync("/api/auth/login", new
        {
            email = KotletTestData.Owner.Email,
            password = KotletTestData.Owner.Password
        });
        login.EnsureSuccessStatusCode();

        var token = (await login.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("accessToken").GetString();
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

        var houses = await client.GetFromJsonAsync<JsonElement>("/api/houses");
        var names = houses.EnumerateArray().Select(house => house.GetProperty("name").GetString()).ToArray();
        Assert.Contains(KotletTestData.HouseName, names);
    }

    [Fact]
    public async Task IngredientCatalogue_IsFullySeeded()
    {
        var client = await SignedInClientAsync();

        var ingredients = await client.GetFromJsonAsync<JsonElement>("/api/ingredients");
        var total = ingredients.GetArrayLength();

        // The production seed CSV carries a few hundred rows; the exact count moves as the
        // catalogue grows, so assert the order of magnitude rather than a brittle number.
        Assert.True(total > 200, $"Expected the seeded ingredient catalogue, but found {total} ingredients.");
    }

    [Fact]
    public async Task Recipes_HaveStableIdentifiers()
    {
        var client = await SignedInClientAsync();
        var expectedId = TestIds.Recipe(KotletTestData.RecipeTitle(0));

        var recipe = await client.GetFromJsonAsync<JsonElement>($"/api/recipes/{expectedId}");

        Assert.Equal(KotletTestData.RecipeTitle(0), recipe.GetProperty("title").GetString());
        Assert.Equal(
            KotletTestData.IngredientsPerRecipe,
            recipe.GetProperty("ingredients").GetArrayLength());
    }

    [Fact]
    public async Task MealPlan_IsPopulatedForEveryPlannedDay()
    {
        var client = await SignedInClientAsync();
        var lastDay = KotletTestData.PlanStart.AddDays(KotletTestData.PlannedDays - 1);

        var day = await client.GetFromJsonAsync<JsonElement>($"/api/meal-planner?date={lastDay:yyyy-MM-dd}");
        var planned = day.GetProperty("meals").EnumerateObject()
            .Sum(slot => slot.Value.GetArrayLength());

        Assert.Equal(KotletTestData.PlannedSlots.Length, planned);
    }

    private async Task<HttpClient> SignedInClientAsync()
    {
        var client = factory.CreateClient();
        var login = await client.PostAsJsonAsync("/api/auth/login", new
        {
            email = KotletTestData.Owner.Email,
            password = KotletTestData.Owner.Password
        });
        login.EnsureSuccessStatusCode();
        var token = (await login.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("accessToken").GetString();
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
        return client;
    }
}
